import React, { useEffect, useState } from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import Snackbar from "@mui/material/Snackbar";
import Header from "../Header";
import SideBar from "../SideBar";

import { useDispatch, useSelector } from "react-redux";
import { getMessage, getStatus, toggleSnackbar } from "../../store/snackbar";
import { login } from "../../store/user";
import { getPage } from "../../store/pages";
import { setActivePage as setGlobalPage } from "../../store/pages";
import useIsLoggedIn from "../../hooks/useIsLoggedIn";

const BaseLayout = ({ children }) => {
  const activePage = useSelector(getPage);
  const isLoggedIn = useIsLoggedIn();
  const open = useSelector(getStatus);
  const snbMsg = useSelector(getMessage);
  const dispatch = useDispatch();
  const router = useRouter();

  useEffect(() => {
    if (!isLoggedIn) {
      router.push("/auth/sign-up");
    }
  }, []);

  const setActivePage = (page) => {
    dispatch(setGlobalPage(page));
  };

  const handleClose = (event, reason) => {
    if (reason === "clickaway") {
      return;
    }
    dispatch(toggleSnackbar({ open: false }));
    // setOpen(false);
  };

  return (
    <div className="w-full h-screen flex">
      <Head>
        <title>Kennis Music Fiesta | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SideBar activePage={activePage} setActivePage={setActivePage} />
      <Snackbar anchorOrigin={{ vertical: "bottom", horizontal: "right" }} open={open} autoHideDuration={6000} onClose={handleClose} message={snbMsg} />
      <main className={"bg-[#FBFAFA] h-full flex-grow px-[2.2rem] !pb-[11.4rem] sidebar:pb-[5.2rem] sidebar:px-[5.2rem] py-[2.9rem]  sidebar:py-[6.4rem] overflow-y-scroll scroll_hide"}>
        <Header title={activePage} setActivePage={setActivePage}></Header>
        {children}
        {/* <div className="w-full h-full grid place-items-center text-3xl">🚧 Under Construction...</div> */}
      </main>
    </div>
  );
};

export default BaseLayout;
