const LOGIN_START = 'LOGIN_START';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_FAILED = 'LOGIN_FAILED';
const SET_USER = 'SET_USER';
const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
const SET_AUTO_PAGE = 'SET_AUTO_PAGE';
const GET_TRANSACTIONS_SUCCESS = 'GET_TRANSACTIONS_SUCCESS';
const GET_SINGLE_EVENT = 'GET_SINGLE_EVENT';
const GET_ARTIST_CATALOGUE_SUCCESS = 'GET_ARTIST_CATALOGUE_SUCCESS';
const GET_CARDS_SUCCESS = 'GET_CARDS_SUCCESS';
const SET_FULLSCREEN = 'SET_FULLSCREEN';
const GET_OVERVIEW = 'GET_OVERVIEW';
const GET_EVENTS = 'GET_EVENTS';
const SET_ACTIVE_PAGE = 'SET_ACTIVE_PAGE';
const CREATE_CAMPAIGN = 'CREATE_CAMPAIGN';
const GET_RAFFLE_DRAW = 'GET_RAFFLE_DRAW';
const START_PROGRESSIVE_DRAW = 'START_PROGRESSIVE_DRAW';
const STOP_PROGRESSIVE_DRAW = 'STOP_PROGRESSIVE_DRAW';
const GET_ACTIVE_DRAWS = 'GET_ACTIVE_DRAWS';
const GET_PROGRESSIVE_DRAW_DETAILS = 'GET_PROGRESSIVE_DRAW_DETAILS';
const GET_VENDORS = 'GET_VENDORS';
const ADD_REFERRAL = 'ADD_REFERRAL';
const GET_REFERRALS = 'GET_REFERRALS';
const ADD_VENDOR = 'ADD_VENDOR';

export {
  LOGIN_START,
  LOGIN_SUCCESS,
  LOGIN_FAILED,
  SET_USER,
  GET_USERS_SUCCESS,
  SET_AUTO_PAGE,
  GET_TRANSACTIONS_SUCCESS,
  GET_SINGLE_EVENT,
  GET_ARTIST_CATALOGUE_SUCCESS,
  GET_CARDS_SUCCESS,
  SET_FULLSCREEN,
  GET_OVERVIEW,
  GET_EVENTS,
  SET_ACTIVE_PAGE,
  CREATE_CAMPAIGN,
  GET_RAFFLE_DRAW,
  START_PROGRESSIVE_DRAW,
  STOP_PROGRESSIVE_DRAW,
  GET_ACTIVE_DRAWS,
  GET_PROGRESSIVE_DRAW_DETAILS,
  GET_VENDORS,
  ADD_REFERRAL,
  GET_REFERRALS,
  ADD_VENDOR,
};
