const LOGIN_START = 'LOGIN_START';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_FAILED = 'LOGIN_FAILED';
const SET_USER = 'SET_USER';
const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
const SET_AUTO_PAGE = 'SET_AUTO_PAGE';
const GET_TRANSACTIONS_SUCCESS = 'GET_TRANSACTIONS_SUCCESS';
const GET_SINGLE_EVENT_SUCCESS = 'GET_SINGLE_EVENT_SUCCESS';
const GET_ARTIST_CATALOGUE_SUCCESS = 'GET_ARTIST_CATALOGUE_SUCCESS';
const START_ON_EVENT_DRAW_SUCCESS = 'START_ON_EVENT_DRAW_SUCCESS';
const GET_CARDS_SUCCESS = 'GET_CARDS_SUCCESS';
const GET_AUTOMATED_DRAW_SETTINGS_SUCCESS =
  'GET_AUTOMATED_DRAW_SETTINGS_SUCCESS';
const ACTIVATE_WEEKLY_DRAW_SETTINGS = 'ACTIVATE_WEEKLY_DRAW_SETTINGS';
const GET_WEEKLY_DRAW_SETTINGS = 'GET_WEEKLY_DRAW_SETTINGS';
const GET_WEEKLY_DRAW = 'GET_WEEKLY_DRAW';
const CHECK_WEEKLY_DRAW_BTN = 'CHECK_WEEKLY_DRAW_BTN';
const UPDATE_WEEKLY_DRAW_SETTINGS = 'UPDATE_WEEKLY_DRAW_SETTINGS';
const GET_EVENT_DRAW_SETTINGS = 'GET_EVENT_DRAW_SETTINGS';
const UPDATE_EVENT_DRAW_SETTINGS = 'UPDATE_EVENT_DRAW_SETTINGS';
const ACTIVATE_EVENT_DRAW_SETTINGS = 'ACTIVATE_EVENT_DRAW_SETTINGS';
const GET_EVENT_DRAW = 'GET_EVENT_DRAW';
const CHECK_EVENT_DRAW_BTN = 'CHECK_EVENT_DRAW_BTN';

export {
  LOGIN_START,
  LOGIN_SUCCESS,
  LOGIN_FAILED,
  SET_USER,
  GET_USERS_SUCCESS,
  SET_AUTO_PAGE,
  GET_TRANSACTIONS_SUCCESS,
  GET_SINGLE_EVENT_SUCCESS,
  GET_ARTIST_CATALOGUE_SUCCESS,
  START_ON_EVENT_DRAW_SUCCESS,
  GET_CARDS_SUCCESS,
  GET_AUTOMATED_DRAW_SETTINGS_SUCCESS,
  ACTIVATE_WEEKLY_DRAW_SETTINGS,
  GET_WEEKLY_DRAW_SETTINGS,
  GET_WEEKLY_DRAW,
  CHECK_WEEKLY_DRAW_BTN,
  UPDATE_WEEKLY_DRAW_SETTINGS,
  GET_EVENT_DRAW_SETTINGS,
  UPDATE_EVENT_DRAW_SETTINGS,
  ACTIVATE_EVENT_DRAW_SETTINGS,
  GET_EVENT_DRAW,
  CHECK_EVENT_DRAW_BTN,
};
