import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import SideBar from "../components/SideBar";
import Header from "../Components/Header";

export default function Home() {
  return (
    <div className="w-screen h-screen flex">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SideBar />
      <main className={"bg-slate-500 h-full flex-grow px-[52px] py-[64px]"}>
        <Header></Header>
        <div className="w-full h-full grid place-items-center text-3xl">🚧 Under Construction...</div>
        {/* <h1 className="text-3xl text-gray-700 font-bold">Kennis Easter Fiester</h1>
        <h1 className="h1">Tickets</h1> */}
      </main>
    </div>
  );
}
